language: ruby
sudo: false
cache: bundler
script: 'bundle exec rubocop && bundle exec rake spec:unit --trace'
after_script: 'echo `env`'
rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3
  - jruby-9.2.6.0
  - ruby-head
  - jruby-head
env:
  - DB=sqlite
  - DB=postgresql
  - DB=mysql

addons:
  postgresql: '9.4'

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-9.2.6.0

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fde2367248d53de4fe70
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start:   never   # options: [always|never|change] default: always
